### ISSUE TITLE
Maltego entities install, what about transforms?

### ISSUE THREAD

**Issue by NetwarSystem** [i3visio/osrframework#299]
I was forced to reset my Maltego config earlier this week, I'm trying to install osrframework, and there are problems.

These instructions lead to all of the entities I expect.

https://github.com/i3visio/osrframework/blob/master/doc/MALTEGO_CONFIGURATION.md

But there is nothing about getting the actual transforms installed. Is there other documentation I should consult?

**Comment by i3visio** [comment]
Sorry for the delay. In 0.17.x and below, transforms are automatically added to the path. The .mtz file that is being created will try to find them in the path once loaded into Maltego so that Maltego Transforms should have been loaded with the i3visio.entities at once. We are working on a fix for this that will be released soon together with 0.18.0 (it is being cooked right now!). Hope you'll find that fixed!

Thanks for the report and we will keep you posted once this is released!

**Comment by i3visio** [comment]
Just a side note. Is this happening on a Window, GNU/Linux or MacOS system?

**Comment by NetwarSystem** [comment]
Gonna close this, try again with a more recent version of all things involved.
