### ISSUE TITLE
Multiple errors in entify.py

### ISSUE THREAD

**Issue by Mi-Al** [i3visio/osrframework#304]
Hello! I try to run entify.py module in Kali Linux (OSRFramework 0.18.0) and in BlackArch (OSRFramework 0.17.3), for example:

`entify.py -w 'https://kali.tools/?page_id=292' -r 'all'`

But I get an arror:

> Traceback (most recent call last):
>   File "/usr/bin/entify.py", line 11, in <module>
>     load_entry_point('osrframework==0.18.0', 'console_scripts', 'entify.py')()
>   File "/usr/lib/python2.7/dist-packages/osrframework/entify.py", line 289, in main
>     if args.license:
> AttributeError: 'Namespace' object has no attribute 'license'

Fix for the error is to add line into the entify.py source:

`    groupMainOptions.add_argument('--license', required=False, action='store_true', default=False, help='shows the GPLv3+ license and exists.')`

But after that I get one more error:

> Traceback (most recent call last):
>   File "/usr/bin/entify.py", line 11, in <module>
>     load_entry_point('osrframework==0.18.0', 'console_scripts', 'entify.py')()
>   File "/usr/lib/python2.7/dist-packages/osrframework/entify.py", line 323, in main
>     print(str(now) + "\tA summary of the results obtained are shown in the following table:\n")
> UnboundLocalError: local variable 'now' referenced before assignment

And so on. They are pretty easy to fix and I tried to push a commit, but I have no permissions.

**Comment by i3visio** [comment]
Thanks for the report. We are marking this to be fixed for 0.18.1. We'll probably release the fix this weekend.

**Comment by i3visio** [comment]
Fixed in the previous commit. We have also added you to `AUTHORS.md` because of the details on how to fix them. 

Ah! With regard to the permissions issue commented before, it is expected in Github. For the next time, it's better to fork the repo, commit the changes to your forked repo and from the Github page of your own repo ask for a pull request. Only then we will be emailed by Github to merge the changes and confirm them!
